version: "3.9"
services:
  python:
    build:
      dockerfile: Dockerfile
    links:
    - postgres
    ports:
    - "80:80"
    depends_on:
    - postgres
  postgres:
    image: "postgres:15.1-alpine"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=randych_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=zadowbalo55
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local