version: "3.9"
services:
  python:
    build:
      dockerfile: Dockerfile
    links:
    - postgres
    ports:
    - "5000:5000"
    depends_on:
    - postgres
  postgres:
    image: "postgres:15.1-alpine"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=randych_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=zadowbalo55
    volumes:
      - ./mydb.sql:/docker-entrypoint-initdb.d/mydb.sql
volumes:
  db:
    driver: local