version: "3.9"
services:
  db:
    build:
      dockerfile: Dockerfile-2
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zadowbalo55
      POSTGRES_DB: randych_db
    ports:
      - "5432:5432"
  python_api:
    build:
      dockerfile: Dockerfile
    container_name: python_api
    ports:
      - "5000:5000"
    depends_on:
      - db